### ISSUE TITLE
The "File" module should have a "from_url" parameter

### ISSUE THREAD

**Issue by mpdehaan** [opsmop/opsmop#13]
File module should be able to fetch URLs.  It should not replace existing files unless a flag is specified (force may be ok, could be a better name).

**Comment by kdbeall** [comment]
Working on this!

**Comment by mpdehaan** [comment]
Awesome!

My thoughts are probably that it should just call wget or curl (curl isn't always installed), but a dependency on something basic isn't a problem either.

One scenario that we *sometimes* get into with downloading when there are proxy servers is it helps to be able to set environment variables to use the proxy (or not).  One place I worked ended up having two different proxy servers. If we end up just using curl, this "just works".  So if it does a shutil.which() and just raises an error if curl isn't there, that's probably ok.

I need to add a note to make an environment resource for later.

**Comment by kdbeall** [comment]
What are your thoughts on using [urllib.request](https://docs.python.org/3.7/library/urllib.request.html#urllib.request.urlopen)?
The download would fail when curl is not installed if it depended on curl.

**Comment by mpdehaan** [comment]
So that looks really clean. I was initially thinking it didn't support HTTP environment variables, but that's not the case:

    "In addition, if proxy settings are detected (for example, when a *_proxy environment variable like 
    http_proxy is set), ProxyHandler is default installed and makes sure the requests are handled 
    through the proxy."

If it ever became a problem that we needed more speed or options we could deal with that later.

However, my initial thought was all about performance, and I just found this:

https://stackoverflow.com/questions/15461995/python-requests-vs-pycurl-performance

As many people will be installing with pip, we *could* use pycurl, but than that will die when libcurl isn't installed, and just telling them to install curl vs libcurl seems somewhat easier.

And, I suspect, it might be faster.

While I suspect, pycurl is stable, it hasn't had a commit in 6 months.

Which brings me to my other philosophical point - the more we depend on stable command lines vs potentially unstable libraries, the less maintaince work I have to do.

I would shell out to curl using "self.command", which also honors the existing "timeout" parameter in the Resource base class.  The class should definitely *raise* the default timeout on the module though, in case that isn't specified.

Finally the last good reason to use curl is we can add a Resource parameter like "curl_opts", allowing easy customization of the resource for basically anything we didn't already forsee in the code, without having to add code for all of those possibilities.

**Comment by mpdehaan** [comment]
To be clear, I see absolutely nothing wrong with urllib3 or requests, just not for this particular use case, seeing it's most commonly going to be used for fetching large-ish RPMs and tarballs.

**Comment by kdbeall** [comment]
Playing around with curl 
https://github.com/kdbeall/curl-experiments

**Comment by kdbeall** [comment]
@mpdehaan I feel a bit lost working on this with the Shell module! I'd like to do something like this but with the Shell module.
        
    call(["curl","https://tools.ietf.org/rfc/rfc1149.txt", "-o", "foo.txt"])

I was reading the [docs](http://docs.opsmop.io/modules/module_shell.html#module-shell) and the example was this --- where variables a,b,c were stored in a dictionary.
    
    Shell(T("echo {{ a }} {{ b }} {{ c }}"))

I hope what I'm asking makes sense!

**Comment by kdbeall** [comment]
Arguably I could do something like Shell("curl " + self.url + " -o " + self.name) but I think doing that would mean vulnerability to an injection attack. So, there is a need to properly parameterize it.

**Comment by mpdehaan** [comment]
Well the code in question is something we're aiming to put curl support inside the *File* module not shell, but let me speak to the injection question first.  

Generally speaking, yes, if you allow user input to be inserted inside a shell command that input *can* of course be executed by the calling program.

The question then is, where does user input come from?  In our case, it's trusted content *MOST* of the time, it's the checked in to git, and that is already running with privileged access on the system.  This is to say that yes, a policy file can ALREADY include "rm -rf /", by design.

Users have to be careful, of course, when they are executing content they don't understand, but in these cases 99.999999% of the time they wrote the content, and they are responsible for the values of variables they pass in.  For instance, we already provide a module that can install any package, and if that is possible, it can be used to install "bad" things.  At this point we realistically have to trust the content, but that's not to say - you're right - that we should largely try to bypass the shell when running modules.  I need to make a note about this, this is dead on.

There *ARE* some cases where variables from the system, if used as parameters to certain modules, could be bad.  For instance, UserFacts has this problem in any config management system - an untrusted host could return something untrustworthy in a variable, and it's worth making a note of that in the docs that you need to be careful where that value is used.  Still, using those values are safe almost anywhere except directly for certain module parameters.

So... how to bypass the shell... that's the question.

When using modules like subprocess, which both the Shell module and the internal function "self.command", use, you can always pass in an array of parameters instead of a string.  In those cases, what happens is the shell is *not* used to execute the command, and it's not going to suffer from possible shell injection - characters like ";" and so on do not apply.  I have wrappers around this for opsmop to keep things simple, but that's true in regular python as well.

So how to execute commands in opsmop provider code?

If you look through the code - I recommend yum.py - you'll see several uses of "self.test" and "self.run", which are both wrappers around my Command class, which are wrappers around subprocess.

so, the most basic example would be:

self.run(["curl", self.from_url, "-o", self.name], ...)

The "should" planning should only decide to download the file if "self.name" does not exist, and the the "do" part of the logic can get the job done by just running curl.

Curl will fail if there are any problems, so no additional error handling is required if you just call self.run.

Let me know if there are other questions.... I wanted to over-explain the security question because you're absolutely *RIGHT* that it's a better practice to not execute strings like that, even though the content is largely trusted, and it's worth correcting that before we get too far into module development.  I'll open up a ticket on that, thanks!

**Comment by mpdehaan** [comment]
I added a ticket for me here: https://github.com/opsmop/opsmop/issues/30

you can just do "self.run(["curl", ...])" and should be good to go.
