### ISSUE TITLE
Let the package modules take lists

### ISSUE THREAD

**Issue by mpdehaan** [opsmop/opsmop#41]
The name field for the package modules should take a list, allowing installs of multiple packages at once.

The apt, yum, and dnf modules should all be modified to ",".join() the name parameter if it is a list, and that is about it.

List may not work with 'version' and should probably raise a ValidationError in the type.

**Comment by GrugLife** [comment]
hi @mpdehaan, I can work on this issue.  

One question, does this need to be done on the providers\package\package.py or types\package.py file (or another file I may be overlooking)?

Thank you

**Comment by GrugLife** [comment]
Thank you for the explanation.  It is definitely more complex than I initially thought.  I'll give it a go.

**Comment by mpdehaan** [comment]
Excellent!

Note that I gave some potentially bad advice above... it is important that when multiple commands are used, the CLI results in *one* command, because the whole point of doing this is because the package managers can be slow.

So I don't think we  can really reuse the existing plan/apply code, but it would be still great if it could be mostly generic, but if they no longer can, that is also ok.

I realize this is asking to update 3 different package providers and that's a lot of work.

Do we want to just advise that if folks want to efficiently install 10 packages they should just use the shell command?

This is probably fine.

I haven't played around enough with dnf to know if it still has the multiple-invocation speed issues, but if it does not, and apt-fast is good (there was a proposal to use it instead of apt if installed), maybe we don't need this anymore?

**Comment by mpdehaan** [comment]
To put it another way, opsmop is already pretty asynchronous - this would save some clock time, but it would not reduce parallelism to have multiple resources the way it did in ansible, where it had to wait for every host to finish.

In saving clock time, there would be some crimes to readability committed, so if multiple dnf executions is not bad (I'll need to try this) and multiple apt-fast executions isn't bad (multiple apt executions already isn't that bad), maybe that is our answer.

The shell command isn't really a problem in that mode anyway, because the yum shell command is already not going to download things when it doesn't have to.

Thoughts?

**Comment by GrugLife** [comment]
I agree, if running multiple dnf and multiple apt-fast executions isn't bad, then lets roll with that.

Once you try out the multiple dnf executions, let me know how it works and if you want to proceed with this route.  In the meantime, I'll look for another issue to tackle.

**Comment by mpdehaan** [comment]
Yeah any module you think you might need in your automation is *possibly* a good fit.  Maybe post up on talk.msphere.io first if you have any questions/ideas,  I may not include *everything* in core.

The wait module might be interesting, if you have a use for it.

https://github.com/opsmop/opsmop/issues/15

This is commonly needed to wait for a service to be up before talking to it.

Another option might be a very simple module that can make Rest requests with arbitrary payloads, or teaching the Echo module to send messages to a service like Slack and HipChat (it could probably read connection information from the UserDefaults class, and then say "to='slack' or to='hipchat')

**Comment by mpdehaan** [comment]
Quick update - the slack suggestion is not a good one because the connection info would need to be transferred to the remote as module parameters, and in push mode that would generate a lot of traffic.  Making it possible to add callbacks in defaults.toml and *then* adding a slack callback that just sends start/finish results would be a better way to go.  Didn't mean to be suggesting work, just going through what might be easy things to add if you didn't have anything particular in mind.

If you've got a particular use case to solve, that's better!

**Comment by GrugLife** [comment]
No worries suggesting more work.  I am new to working on open source projects so it helps to what needs to be done than just work on particular use cases.

I'll work on either this Slack suggestion or the wait module.

**Comment by mpdehaan** [comment]
Yeah just want to be clear- the slack one is probably a lot better *ignored* and done in Vespene (which already has a slack plugin) or another CI/CD server that does. It gets weird because the push mode callbacks and the regular callbacks work differently, and duplicate events are hard to avoid (it could get annoying quick)

The wait module would get a fair amount of mileage.

Another good one would be a FileReplace("foo/path.txt", match=match_pattern, replace_with=replace_) type module that uses basic regexes.

That's probably going to be very short, but also is going to get used a ton.

**Comment by GrugLife** [comment]
Sounds good.  I will work on these two modules.

**Comment by mpdehaan** [comment]
Closing this ticket because I think taking lists would be intrusive to the way most of the providers work.... at least for now.
