### ISSUE TITLE
missing method summarize in LocalCliCallbacks

### ISSUE THREAD

**Issue by FooBarQuaxx** [opsmop/opsmop#54]
**Describe the bug**
Method `LocalCliCallbacks.summarize` is not defined.

**To Reproduce**
`python opsmops-demo/contents/errors.py --local --apply`

**Expected behavior**
Define the missing method.

**Comment by mpdehaan** [comment]
Sorry about that one - I was working on the CLI output path recently and have been testing playbooks that didn't fail.  I've removed the method call, since it is no longer used.

Thank you!
